<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [ ]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [ ]:
import folium
import pandas as pd

In [ ]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [ ]:
## Task 1: Mark all launch sites on a map
# List unique launch sites with their coordinates
unique_sites = spacex_df[['Launch Site', 'Lat', 'Long']].drop_duplicates()
print(unique_sites)

In [8]:
import folium

map_center = [unique_sites['Lat'].mean(), unique_sites['Long'].mean()]
launch_map = folium.Map(location=map_center, zoom_start=5)

for idx, row in unique_sites.iterrows():
    folium.Marker(
        location=[row['Lat'], row['Long']],
        popup=row['Launch Site']
    ).add_to(launch_map)

launch_map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [6]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [9]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [10]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [11]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [12]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
import folium

# Assuming you have a DataFrame `launch_sites_df` with columns: 'Launch Site', 'Lat', 'Long'
# Example: launch_sites_df = spacex_df[['Launch Site', 'Lat', 'Long']].drop_duplicates()

# Center the map around the average coordinates
map_center = [launch_sites_df['Lat'].mean(), launch_sites_df['Long'].mean()]
launch_map = folium.Map(location=map_center, zoom_start=5)

# Add Circle markers for each launch site
for idx, row in launch_sites_df.iterrows():
    folium.Circle(
        location=[row['Lat'], row['Long']],
        radius=5000,  # radius in meters
        color='blue',
        fill=True,
        fill_color='cyan',
        fill_opacity=0.5,
        popup=row['Launch Site']
    ).add_to(launch_map)

# Display the map
launch_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

In [13]:
spacex_df.count()

Launch Site    56
Lat            56
Long           56
class          56
dtype: int64

In [14]:
# Task 2: Mark the success/failed launches for each site on the map
import folium
import pandas as pd

# Assuming spacex_df is already loaded with your 56 rows

# Example: Create a map centered on average coordinates
site_map = folium.Map(location=[spacex_df['Lat'].mean(), spacex_df['Long'].mean()], zoom_start=5)

# Create MarkerCluster
marker_cluster = MarkerCluster()

# Add markers from spacex_df
for index, record in spacex_df.iterrows():
    marker_color = 'green' if record['class'] == 1 else 'red'  # or use your marker_color column if created
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color=marker_color),
        popup=f"Site: {record['Launch Site']}\nLaunch outcome: {'Success' if record['class'] == 1 else 'Failure'}"
    )
    marker_cluster.add_child(marker)

site_map.add_child(marker_cluster)

# Display the map
site_map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [21]:
spacex_df.head(10)

   Launch Site        Lat       Long  class marker_color
0  CCAFS LC-40  28.562302 -80.577356      0          red
1  CCAFS LC-40  28.562302 -80.577356      0          red
2  CCAFS LC-40  28.562302 -80.577356      0          red
3  CCAFS LC-40  28.562302 -80.577356      0          red
4  CCAFS LC-40  28.562302 -80.577356      0          red
5  CCAFS LC-40  28.562302 -80.577356      0          red
6  CCAFS LC-40  28.562302 -80.577356      0          red
7  CCAFS LC-40  28.562302 -80.577356      0          red
8  CCAFS LC-40  28.562302 -80.577356      0          red
9  CCAFS LC-40  28.562302 -80.577356      0          red

In [23]:
# Filter the row where LaunchSite matches the coastline site
coastline_row = spacex_df[spacex_df['Launch Site'] == 'CCAFS LC-40'].iloc[0]

# Extract latitude and longitude
coastline_lat = coastline_row['Lat']
coastline_lon = coastline_row['Long']

print("Coastline Latitude:", coastline_lat)
print("Coastline Longitude:", coastline_lon)

Coastline Latitude: 28.56230197
Coastline Longitude: -80.57735648

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [16]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [17]:
import pandas as pd

# Define the function to assign marker color based on 'class' value
def assign_marker_color(class_value):
    if class_value == 1:
        return 'green'
    else:
        return 'red'

# Apply the function to create a new 'marker_color' column in spacex_df
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)

# Verify the result
print(spacex_df[['Launch Site', 'class', 'marker_color']].tail())

     Launch Site  class marker_color
51  CCAFS SLC-40      0          red
52  CCAFS SLC-40      0          red
53  CCAFS SLC-40      0          red
54  CCAFS SLC-40      1        green
55  CCAFS SLC-40      0          red

In [18]:
# Define a function to assign marker colors based on 'class' column
def assign_marker_color(class_value):
    return 'green' if class_value == 1 else 'red'

# Apply the function to create the 'marker_color' column
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)

In [19]:
print(spacex_df.columns)

Index(['Launch Site', 'Lat', 'Long', 'class', 'marker_color'], dtype='object')

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [20]:
import folium
from folium.plugins import MarkerCluster

# Create the base map centered on average coordinates
site_map = folium.Map(location=[spacex_df['Lat'].mean(), spacex_df['Long'].mean()], zoom_start=5)

# Create MarkerCluster object
marker_cluster = MarkerCluster()

for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color=record['marker_color']),
        popup=f"Site: {record['Launch Site']}\nLaunch outcome: {'Success' if record['class'] == 1 else 'Failure'}"
    )
    marker_cluster.add_child(marker)

# Add MarkerCluster to the map
site_map.add_child(marker_cluster)

# Display the map
site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [25]:
# TASK 3: Calculate the distances between a launch site to its proximities
import math

def haversine(lat1, lon1, lat2, lon2):
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    
    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    
    r = 6371  # Earth radius in km
    return c * r

# Coordinates of first launch site
launch_site_lat = spacex_df.loc[0, 'Lat']
launch_site_lon = spacex_df.loc[0, 'Long']

# Example coastline coordinates near launch site
coastline_lat = 28.56300
coastline_lon = -80.57000

distance = haversine(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distance: {distance:.2f} km")

Distance: 0.72 km

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [26]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [27]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [29]:
import math
import pandas as pd

# Haversine function to calculate distance in km
def calculate_distance(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    r = 6371  # Earth radius in km
    return c * r

# Example launch site coordinates
launch_site_lat = 28.5623
launch_site_lon = -80.5774

# Example coastline coordinates DataFrame
coastline_coords = pd.DataFrame({
    'Latitude': [28.56367, 28.56400, 28.56000],  # replace/add actual coastline latitudes
    'Longitude': [-80.57163, -80.57200, -80.57000]  # replace/add actual coastline longitudes
})

# Calculate distances from launch site to each coastline point
coastline_coords['Distance_km'] = coastline_coords.apply(
    lambda row: calculate_distance(launch_site_lat, launch_site_lon, row['Latitude'], row['Longitude']), axis=1)

# Find the closest coastline point
closest_point = coastline_coords.loc[coastline_coords['Distance_km'].idxmin()]

print("Closest coastline point:")
print(closest_point)

Closest coastline point:
Latitude       28.564000
Longitude     -80.572000
Distance_km     0.560227
Name: 1, dtype: float64

In [106]:
import folium
from folium.features import DivIcon

# Assuming you have:
# closest_point with 'Latitude' and 'Longitude'
# launch_site coordinate: (launch_site_lat, launch_site_lon)
# distance value in kilometers: closest_point['Distance_km']

# Create your base map centered around the launch site
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=10)

# Marker for the launch site
folium.Marker(
    location=[launch_site_lat, launch_site_lon],
    popup="Launch Site",
    icon=folium.Icon(color='blue')
).add_to(site_map)

# Marker for the closest coastline point
coastline_coord = [closest_point['Latitude'], closest_point['Longitude']]
distance = closest_point['Distance_km']

distance_marker = folium.Marker(
    location=coastline_coord,
    icon=DivIcon(
        icon_size=(150,36),
        icon_anchor=(0,0),
        html=f'<div style="font-size: 12px; color:#d35400;"><b>{distance:.2f} KM</b></div>'
    )
)

distance_marker.add_to(site_map)

# Optional: add a marker for the coastline point itself
folium.Marker(
    location=coastline_coord,
    popup="Closest Coastline",
    icon=folium.Icon(color='green')
).add_to(site_map)

# Display the map
site_map

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [30]:
import folium

# Example coordinates:
launch_site_coord = [launch_site_lat, launch_site_lon]  # e.g., [28.5623, -80.5774]
coastline_coords_list = coastline_coords[['Latitude', 'Longitude']].values.tolist()  # list of [lat, lon]

# Combine launch site coordinate and coastline coordinates into one list to draw the line
coordinates = [launch_site_coord] + coastline_coords_list

# Create PolyLine
lines = folium.PolyLine(locations=coordinates, weight=2, color='blue')

# Add PolyLine to the map
site_map.add_child(lines)

# Display the map
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [31]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
import folium
from folium.features import DivIcon

# Example launch site coordinate
launch_site_lat = 28.5623
launch_site_lon = -80.5774
launch_site_coord = [launch_site_lat, launch_site_lon]

# Create base map centered on launch site
site_map = folium.Map(location=launch_site_coord, zoom_start=10)

# Add launch site marker
folium.Marker(
    location=launch_site_coord,
    popup="Launch Site",
    icon=folium.Icon(color='blue')
).add_to(site_map)

# Example closest features with coordinates and distances (replace with your data)
features = {
    'Closest City': {'coord': [28.5700, -80.5800], 'distance_km': 1.2},
    'Closest Railway': {'coord': [28.5550, -80.5900], 'distance_km': 2.5},
    'Closest Highway': {'coord': [28.5650, -80.5600], 'distance_km': 3.1}
}

for name, info in features.items():
    coord = info['coord']
    distance = info['distance_km']

    # Add marker with distance label
    distance_marker = folium.Marker(
        location=coord,
        icon=DivIcon(
            icon_size=(150,36),
            icon_anchor=(0,0),
            html=f'<div style="font-size: 12px; color:#d35400;"><b>{distance:.2f} KM</b></div>'
        ),
        popup=f"{name} - {distance:.2f} KM"
    )
    distance_marker.add_to(site_map)

    # Add a marker icon for the feature
    folium.Marker(
        location=coord,
        popup=name,
        icon=folium.Icon(color='green')
    ).add_to(site_map)

    # Draw a line from launch site to feature
    line = folium.PolyLine(locations=[launch_site_coord, coord], color='purple', weight=2)
    site_map.add_child(line)

# Display the map
site_map

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>